spring.config.import=optional:file:./.env[.properties]

spring.application.name=EvalAI
# Server
server.port=${SERVER_PORT:8081}

# Database — reads from Docker env vars
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/evalai}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:postgres}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:postgres}

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# JWT
app.jwt.secret=${APP_JWT_SECRET:sdXixFgrbZi3XFu6q+hABS8k+h4wS7CBReALG0cCI5g=}
app.jwt.expiration=${APP_JWT_EXPIRATION:86400000}
app.java.base-url=http://evalai-java:8081
# Upload path — reads from Docker env var
app.upload.base-path=${APP_UPLOAD_BASE_PATH:/app/uploads}

# File Upload Limits â increased for answer sheet PDFs
spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=200MB

# Python service
app.python.base-url=${APP_PYTHON_BASE_URL:http://evalai-python:8000}
app.pipeline.callback-secret=StUfr4l3Bm+xWJ+vz+9kG/cKhwlEFQ3fOEa2Fx4Sx7c=

# gRPC
app.grpc.host=${APP_GRPC_HOST:localhost}
app.grpc.port=${APP_GRPC_PORT:50051}
app.pipeline.skip-cpp=${APP_PIPELINE_SKIP_CPP:true}


